name: Run base

on:
  schedule:
    - cron:  '*/15 * * * *'
  push:
      branches:
        - main

env:

  ARBZERO_APPCODE: "base_dola_usdc"
  ARBZERO_TRADER: "0x2943ec8fb4e9b3e1ca73700869856be35aeee63e"
  ARBZERO_RPC_URL: ${{ secrets.BASE_RPC_URL }} 
  ARBZERO_SIGNER: ${{ secrets.BASE_SIGNER_PK }}
  ARBZERO_TOKEN_A: "0x4621b7A9c75199271F773Ebd9A499dbd165c3191"
  ARBZERO_TOKEN_B: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
  ARBZERO_A_TO_B_RATE: "0.9905"
  ARBZERO_B_TO_A_RATE: "1.0121"
  ARBZERO_CHAIN: base

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Checkout Arbzero
        uses: actions/checkout@v4
        with:
          repository: trovezero/arbzero
          ref: main
          token: ${{ secrets.PAT_ANYONE_READS_ARBZERO }}
          path: arbzero
      - name: Install Dependencies
        working-directory: ./arbzero
        run: |
          yarn install --frozen-lockfile
          yarn add --dev typescript ts-node
      - name: Run TypeScript Project
        working-directory: ./arbzero
        run: yarn start
      